# SPDX-FileCopyrightText: 2022 Stephan Druskat <pyswh@sdruskat.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Code coverage

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: Codecov
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install requirements
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry install --with dev
      - name: Run tests and collect coverage
        run: poetry run pytest --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry install --with dev
      - name: Run tox
        run: |
          poetry run tox -e py
          sed -i "s/<source>\/home\/runner\/work\/pyswh\/pyswh<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/work/pyswh/pyswh/coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}